config:
  variables:
    payload:
      name: Sasa
      surname: Savic
      weight: 90
      height: 185
      addresses:
        - name: Exhibition Street Office
          address: '242 Exhibition Street, Melbourne CBD'
        - name: LaTrobe Street Office
          address: '300 LaTrobe Street, Melbourne CBD'
      interests:
        - software engineering
        - data science
        - quantum physics
        - gym
  phases:
    - duration: 20
      arrivalRate: 10
      name: Execute tests at 10 user per second for 5 minutes
  defaults:
    headers:
      x-telstra-mocktillary-id: '{{ $uuid }}'
scenarios:
  - name: 200 OK Response
    flow:
      - post:
          url: /api/v1/mock
          json:
            settings:
              failureProbability: 0
            body:
              '[object Object]': null
          expect:
            - statusCode: 200
  - name: Abrupt Connection Reset with 1.0 Probability
    flow:
      - post:
          url: /api/v1/mock
          json:
            settings:
              failureProbability: 1
              simulators:
                connection: connection_reset_by_peer
            body: '{{ postPayload }}'
          expect:
            - statusCode: 200
  - name: Duplicate Content-Length Header With 1.0 Probability
    flow:
      - post:
          url: /api/v1/mock
          json:
            settings:
              failureProbability: 1
              simulators:
                header:
                  duplicateHeader: Content-Length
            body:
              '[object Object]': null
          expect:
            - statusCode: 400
  - name: Incorrect Content Length with 1.0 Probability
    flow:
      - post:
          url: /api/v1/mock
          json:
            settings:
              failureProbability: 1
              simulators:
                header:
                  incorrectContentLength: true
            body:
              '[object Object]': null
          expect:
            - statusCode: 400
