config:
  variables:
    payload:
      name: Sasa
      surname: Savic
      weight: 90
      height: 185
      addresses:
        - name: Exhibition Street Office
          address: 242 Exhibition Street, Melbourne CBD
        - name: LaTrobe Street Office
          address: 300 LaTrobe Street, Melbourne CBD
      interests:
        - software engineering
        - data science
        - quantum physics
        - gym
  phases:
    - duration: 20
      arrivalRate: 10
      name: "Execute tests at 10 user per second for 5 minutes"
  defaults:
      headers:
          x-telstra-mocktillary-id: "{{ $uuid }}"